<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Images/icon.ico</ApplicationIcon>
        <PublishSingleFile>true</PublishSingleFile>
        <SourceRevisionId>$([System.DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ"))</SourceRevisionId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
        <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Nito.AsyncEx.Coordination" Version="5.1.2"/>
    </ItemGroup>

</Project>
